title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          text:
            type: textarea
          category:
            type: text
          client:
            type: text
          link:
            type: url

  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        ratio: 1/1
